### ISSUE TITLE
Not able to switch to a channel using action media_player.play_media

### ISSUE THREAD

**Issue by canedje** [Sholofly/lghorizon#236]
**Describe the bug**
I do use NodeRed to switch on media player and going to channel 1.
This worked very well for years
I do use action: mediaplayer.play_media
data:
{
    "media_content_id": "1",
    "media_content_type": "channel"
}

Now after update of HA to 2026.2.0 it is not working anymore
I get  error in NodeRed:
```
5-2-2026, 20:12:14[node: Kanaal kiezen: 1](http://192.168.2.240:1881/#)
msg : error
error
name: "HomeAssistantError"
message: "'LGHorizonDevice' object has no attribute 'playing_info'"
stack: string
HomeAssistantError: 'LGHorizonDevice' object has no attribute 'playing_info'
    at p (/data/node_modules/node-red-contrib-home-assistant-websocket/dist/common/errors/inputErrorHandler.js:1:1032)
    at m (/data/node_modules/node-red-contrib-home-assistant-websocket/dist/common/errors/inputErrorHandler.js:1:1318)
    at #t (/data/node_modules/node-red-contrib-home-assistant-websocket/dist/common/controllers/InputOutputController.js:1:1340)
```
and in HA log:
```
Deze fout is ontstaan door een aangepaste integratie.

Logger: lghorizon.lghorizon_models
Bron: custom_components/lghorizon/sensor.py:86
integratie: LG Horizon (documentatie, problemen)
Eerst voorgekomen: 00:23:29 (7 gebeurtenissen)
Laatst gelogd: 19:23:29

Error response from https://spark-prod-nl.gnp.cloud.ziggogo.tv/eng/web/recording-service/customers/12005157_nl/quota: 401, message='Unauthorized', url='https://spark-prod-nl.gnp.cloud.ziggogo.tv/eng/web/recording-service/customers/12005157_nl/quota'
```
and:
```
Logger: lghorizon.lghorizon_models
Bron: runner.py:289
Eerst voorgekomen: 17:13:22 (1 gebeurtenis)
Laatst gelogd: 17:13:22

Error response from https://spark-prod-nl.gnp.cloud.ziggogo.tv/eng/web/linear-service/v2/replayEvent/crid:~~2F~~2Fgn.tv~~2F32207854~~2FEP062640600010,imi:4d3c0de695333b5a2ec6db303f34c8762dc0b8bf?returnLinearContent=true&language=nl: 401, message='Unauthorized', url='https://spark-prod-nl.gnp.cloud.ziggogo.tv/eng/web/linear-service/v2/replayEvent/crid:~~2F~~2Fgn.tv~~2F32207854~~2FEP062640600010,imi:4d3c0de695333b5a2ec6db303f34c8762dc0b8bf?returnLinearContent=true&language=nl'
```
option lghorizon.remote_key_press is still working
Going back to v0.8.4 causing a migration error and not starting of the integration
**Version of the component**
The version of the component as it is installed on your HA: v0.9.0beta5

**Logging**
Enable debug logging and add your log. DO NOT SHARE SENSITIVE DATA SUCH AS PASSWORDS AND ACCOUNT INFO!
You can enable logging by setting up the logging component in HA as follows:
```yaml
logger:
  default: warning
  logs:
    lghorizon: debug
```

**Additional context**

**Comment by Sholofly** [comment]
Yeah my fault. :) Fixed in the new beta6

**Comment by canedje** [comment]
I can confirm it is working again..!!
Thanks for the effort
