### ISSUE TITLE
LG Horizon not working after update v0.7.5

### ISSUE THREAD

**Issue by Braakie** [Sholofly/lghorizon#172]
**Describe the bug**
After the update and a restart, the LG Horizon integration no longer works.

**Version of the component**
v0.7.5

**Logging**
```
2025-02-28 06:39:58.748 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry xxxxxxx@xxxnet.nl for lghorizon
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 637, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/lghorizon/__init__.py", line 64, in async_setup_entry
    await hass.async_add_executor_job(api.connect)
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 59, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.13/site-packages/backoff/_sync.py", line 105, in retry
    ret = target(*args, **kwargs)
  File "/usr/local/lib/python3.13/site-packages/lghorizon/lghorizon_api.py", line 263, in connect
    self._mqtt_client = LGHorizonMqttClient(
                        ~~~~~~~~~~~~~~~~~~~^
        self._auth,
        ^^^^^^^^^^^
    ...<2 lines>...
        self._on_mqtt_message,
        ^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/site-packages/lghorizon/models.py", line 363, in __init__
    mqtt.CallbackAPIVersion.VERSION1,  # disabled because of dependency issue
    ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'paho.mqtt.client' has no attribute 'CallbackAPIVersion'
```
I have the mediabox next from ziggo

**Comment by Sholofly** [comment]
Hi @Braakie, stupid me forgor to add the minimum version requirement for home assistant. That's 2025.3. That means you can only update it to this version  by installing the beta on this moment. I'll change that this morning. You can revert to the previous version. I'm sorry for the inconvenience!

**Comment by Braakie** [comment]
No problem, thnx

**Comment by Sholofly** [comment]
Can you revert to 0.7.4, updat the component information in HACS,  and confirm you don't receive an offer to update to 0.7.6?

**Comment by canedje** [comment]
Also updat 0.7.6 is not working over here

**Comment by Sholofly** [comment]
What ha version are you running?

**Comment by canedje** [comment]
I'm running the latest HA version: 2025.2.5

![Image](https://github.com/user-attachments/assets/0b873c75-1399-42bd-a726-1f7f481dc1ee)
Also going back to 7.4.0 is giving an error
```
Logger: lghorizon.lghorizon_api
Bron: /usr/local/lib/python3.13/site-packages/backoff/_common.py:120
Eerst voorgekomen: 08:39:22 (2 gebeurtenissen)
Laatst gelogd: 08:40:26

Giving up connect(...) after 3 tries (AttributeError: module 'paho.mqtt.client' has no attribute 'CallbackAPIVersion')
```
@Sholofly

**Comment by snhnic** [comment]
Latest version v0.7.6 and it doesn't work. Did not test v0.7.5 How can I revert to 0.7.4?

![Image](https://github.com/user-attachments/assets/4eb46e61-4a91-4349-93d9-a933812ea2b5)

**Comment by keesg60** [comment]
Having the same problem for 0.7.6 and  I'm also having problems going back to 0.7.4

I'm running Home Assistant 2025.2.5

The error I get is:

```
File "/usr/local/lib/python3.13/site-packages/lghorizon/models.py", line 363, in init
mqtt.CallbackAPIVersion.VERSION1, # disabled because of dependency issue
^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'paho.mqtt.client' has no attribute 'CallbackAPIVersion'

```

**Comment by Sholofly** [comment]
Ok, I fixed it (I hope). You can update to v0.7.7. Paho made their change backwards compatible. Let me know if it fixed for you guys. Sorry for the inconvenience.

**Comment by canedje** [comment]
Thanks @Sholofly. Version 0.7.7 did fix the problem.
It is working for me again

**Comment by rjblake** [comment]
Same here - HA v2025.2.5 & LG Horizon v0.7.6. Error in log:

Logger: homeassistant.setup
Source: setup.py:275
First occurred: 9:24:00 AM (1 occurrences)
Last logged: 9:24:00 AM

Setup failed for custom integration 'lghorizon': Requirements for lghorizon not found: ['homeassistant>=2025.3.0']. How can I manually update to 0.7.7 manually, as not showing up in my HA as an update (yet)?

**Comment by keesg60** [comment]
Everything is working again. 
Thanks for the great work.

**Comment by rjblake** [comment]
> Same here - HA v2025.2.5 & LG Horizon v0.7.6. Error in log:
> 
> Logger: homeassistant.setup Source: setup.py:275 First occurred: 9:24:00 AM (1 occurrences) Last logged: 9:24:00 AM
> 
> Setup failed for custom integration 'lghorizon': Requirements for lghorizon not found: ['homeassistant>=2025.3.0']. How can I manually update to 0.7.7 manually, as not showing up in my HA as an update (yet)?

Duh - ignore my request. Was not looking in HACS for the update :) - all working on v0.7.7

**Comment by canedje** [comment]
> Same here - HA v2025.2.5 & LG Horizon v0.7.6. Error in log:
> 
> Logger: homeassistant.setup Source: setup.py:275 First occurred: 9:24:00 AM (1 occurrences) Last logged: 9:24:00 AM
> 
> Setup failed for custom integration 'lghorizon': Requirements for lghorizon not found: ['homeassistant>=2025.3.0']. How can I manually update to 0.7.7 manually, as not showing up in my HA as an update (yet)?

Just update straigh in HACS choosing the right version:
Klik 3 dots right top cornes of the LG Horizon HACS page:

![Image](https://github.com/user-attachments/assets/26c00179-ba00-48a1-97a3-f07e1eaac7c7)

![Image](https://github.com/user-attachments/assets/96889c8f-7af9-4d05-92b3-09ee9bae3ab7)

**Comment by snhnic** [comment]
Top woking again with v0.7.7

**Comment by Braakie** [comment]
I could not go back to an older version, which did not connect anymore. Then I put back a backup from last night where I still had version v0.7.4. Then I did the update to v0.7.7 and that also works.
